baseURL = 'https://delabiemedia.be'
title = "Delabie Media"

theme = "delabiemedia-hugotheme"

disableKinds = ['taxonomy']

[params]
titleDescription = "Videograaf & Videoproductieservices"
titleKeywords = "evenementen, advertenties, reclamevideos, bedrijfsvideo's, ..."

[sitemap]
priority = 0.5

[outputs]
section = ['HTML', 'videositemap']

[outputFormats.videositemap]
mediaType = 'application/xml'
baseName = 'videositemap'
isPlainText = true