baseURL = 'https://delabiemedia.be'
title = "Delabie Media | Videografie & Videoproductieservices | evenementen, advertenties, reclamevideos, bedrijfsvideo's, ..."

theme = "delabiemedia-hugotheme"

disableKinds = ['taxonomy']

[sitemap]
priority = 0.5

[outputs]
section = ['HTML', 'videositemap']

[outputFormats.videositemap]
mediaType = 'application/xml'
baseName = 'videositemap'
isPlainText = true