baseURL = 'https://delabiemedia.be'
languageCode = 'nl-BE'
title = 'Delabie Media'

theme = "delabiemedia-hugotheme"

disableHugoGeneratorInject = true
disableKinds = ['taxonomy']

[sitemap]
priority = 0.5

[outputs]
section = ['HTML', 'videositemap']

[outputFormats.videositemap]
mediaType = 'application/xml'
baseName = 'videositemap'
isPlainText = true