name: Purge CloudFlare cache
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        # preferred
        with:
            cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
            cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
